read docutils module version from __version__ instead of __version_info__
Fixes warning:
AttributeError: module 'docutils' has no attribute '__version_info__'

Change-Id: I007c557bf5060d79f47dae40db4595919b8301b9